### ISSUE TITLE
histmag.org

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/PolishAnnoyanceFilters#2238] opened 2020-06-27 11:11 UTC
https://histmag.org/Rozrywki-w-czasach-staropolskich-bawic-sie-kazdy-moze-20864/
![2020-06-27 13 09 54 histmag org 492c3f3bc3c5](https://user-images.githubusercontent.com/36385327/85920865-bbd2e100-b877-11ea-908a-4faaf8e0442a.png)

**Comment by krystian3w** [comment] 2020-06-28 11:40
Duplicate of #2294

**Closed** 2020-06-28 11:40 UTC
Labels: zatwierdzone, duplikat, inny element

**Comment by krystian3w** [comment] 2021-07-03 15:09
Duplicate of #2294
